#!/usr/bin/env python3
"""Check runtime plugin links, resource reachability, and stale references."""

from __future__ import annotations

from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
PLUGINS = ROOT / "plugins"
LINK = re.compile(r"\[[^\]]+\]\(([^)]+)\)")
REMOTE_HTML = re.compile(
    r'<(?:script|link|img)\b[^>]+(?:src|href)=["\']https?://', re.I
)
BANNED_RUNTIME_TEXT = (
    "plugins/wigtn-plugins/skills/design-system-reference/",
    "frontend-developer 에이전트",
    "PASS면 `/implement`",
    "Generated by /screen-spec",
    "design-system-reference 재활용",
    "Google Fonts/CDN",
)
TEXT_SUFFIXES = {".md", ".json", ".yaml", ".yml", ".py", ".sh", ".html"}


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def main() -> int:
    errors: list[str] = []
    markdown_files = sorted(PLUGINS.rglob("*.md"))
    for path in markdown_files:
        text = read(path)
        for match in LINK.finditer(text):
            target = match.group(1).split("#", 1)[0].strip()
            if not target or target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            if not (path.parent / target).resolve().exists():
                line = text.count("\n", 0, match.start()) + 1
                errors.append(
                    f"{path.relative_to(ROOT)}:{line}: missing link target {target}"
                )

    for plugin in sorted(path for path in PLUGINS.iterdir() if path.is_dir()):
        text_files = [
            path
            for path in plugin.rglob("*")
            if path.is_file() and path.suffix in TEXT_SUFFIXES
        ]
        all_text = {path: read(path) for path in text_files}
        combined = "\n".join(all_text.values())
        for token in BANNED_RUNTIME_TEXT:
            if token in combined:
                errors.append(f"{plugin.name}: stale runtime reference {token!r}")
        for skill in sorted((plugin / "skills").iterdir() if (plugin / "skills").exists() else []):
            if not skill.is_dir():
                continue
            skill_texts = {
                path: text for path, text in all_text.items() if skill in path.parents
            }
            for folder in ("references", "assets", "scripts"):
                resource_root = skill / folder
                if not resource_root.exists():
                    continue
                for resource in resource_root.rglob("*"):
                    if not resource.is_file():
                        continue
                    other_text = "\n".join(
                        text for path, text in skill_texts.items() if path != resource
                    )
                    if resource.name not in other_text:
                        errors.append(
                            f"{resource.relative_to(ROOT)}: bundled resource is unreachable"
                        )

    for template in PLUGINS.rglob("assets/**/*.html"):
        if REMOTE_HTML.search(read(template)):
            errors.append(
                f"{template.relative_to(ROOT)}: output template uses a remote resource"
            )

    if errors:
        print("Plugin resource integrity: FAIL")
        for error in errors:
            print(f"- {error}")
        return 1
    print(
        "Plugin resource integrity: PASS "
        f"({len(markdown_files)} markdown files)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
